name: dikantin_o_l_d
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  carbon_icons: ^0.0.1+2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.17.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
